baseurl = "http://lanzani.nl"
disablePathToLower = true
languageCode = "en-us"
title = "Technical inconsistencies"
theme = 'hugola'

[params]
Domain = "http://www.lanzani.nl"
Name = "lanzani.nl"

[params.sidebar]
search = "http://duckduckgo.com/?q=site%3Alanzani.nl"
blog = "http://blog.lanzani.nl"
cv = "/cv/"
publications = "/publications/"
public = "/public/"

[params.footer]
Contact = "mailto:giovanni at this domain?subject=feedback"
X = "http://twitter.com/gglanzani/"
GitHub = "http://github.com/gglanzani/"
Mastodon = "https://mastodon.social/@gla"
LinkedIn = "http://nl.linkedin.com/pub/giovanni-lanzani/24/618/195"

[outputs]
home = [ "HTML" ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
