baseurl = "http://lanzani.nl"
disablePathToLower = true
languageCode = "en-us"
title = "Technical inconsistencies"
theme = 'hugola'

[params]
Domain = "http://www.lanzani.nl"
Name = "lanzani.nl"

[params.sidebar]
search = "http://duckduckgo.com/?q=site%3Alanzani.nl"
blog = "http://blog.lanzani.nl"
cv = "/cv/"
publications = "/publications/"
public = "/public/"

[outputs]
home = [ "HTML" ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
